# Generated by Django 2.2.2 on 2019-06-22 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(help_text='Escreva uma descricao para voce!', max_length=300)),
            ],
            options={
                'ordering': ['-user'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='oi', help_text='Escreva o assunto que deseja postar.', max_length=50)),
                ('content', models.CharField(default='oi', help_text='No que você esta pensando?', max_length=1000)),
                ('date', models.DateTimeField(default='2015-10-22 20:31:56.248000')),
                ('author', models.ForeignKey(on_delete=models.SET('Usuario Desvinculado'), to='blog.Author')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Deixe um comentario.', max_length=300)),
                ('date', models.DateTimeField(default='2015-10-22 20:31:56.248000')),
                ('Commenter', models.ForeignKey(on_delete=models.SET('Usuario Desvinculado'), to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
