# Generated by Django 2.2.2 on 2019-06-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190622_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Commenter',
            new_name='commenter',
        ),
    ]
